# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/RF-Transmitter/vivado/XC7Z010_QDUC/XC7Z010_QDUC.srcs/sources_1/ip/fir_compiler_1/fir_compiler_1.xci
# IP: The module: 'fir_compiler_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/RF-Transmitter/vivado/XC7Z010_QDUC/XC7Z010_QDUC.srcs/sources_1/ip/fir_compiler_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/RF-Transmitter/vivado/XC7Z010_QDUC/XC7Z010_QDUC.srcs/sources_1/ip/fir_compiler_1/fir_compiler_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Projects/RF-Transmitter/vivado/XC7Z010_QDUC/XC7Z010_QDUC.srcs/sources_1/ip/fir_compiler_1/fir_compiler_1.xci
# IP: The module: 'fir_compiler_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/RF-Transmitter/vivado/XC7Z010_QDUC/XC7Z010_QDUC.srcs/sources_1/ip/fir_compiler_1/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/RF-Transmitter/vivado/XC7Z010_QDUC/XC7Z010_QDUC.srcs/sources_1/ip/fir_compiler_1/fir_compiler_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fir_compiler_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
