webtalk_init -webtalk_dir D:/Projects/RF-Transmitter/vivado/XC7Z010_QDUC/XC7Z010_QDUC.sim/sim_1/behav/xsim/xsim.dir/srrc_filter_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct  8 23:31:00 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4bad9526-75ac-46de-a82b-c9767d2800b1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "474f1a9697b74573a054b532fb577ad6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2012 R2 or Windows 8.1" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2195 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "9504 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "35.95_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8596_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1008293389 -regid "" -xml D:/Projects/RF-Transmitter/vivado/XC7Z010_QDUC/XC7Z010_QDUC.sim/sim_1/behav/xsim/xsim.dir/srrc_filter_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Projects/RF-Transmitter/vivado/XC7Z010_QDUC/XC7Z010_QDUC.sim/sim_1/behav/xsim/xsim.dir/srrc_filter_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Projects/RF-Transmitter/vivado/XC7Z010_QDUC/XC7Z010_QDUC.sim/sim_1/behav/xsim/xsim.dir/srrc_filter_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
